### ISSUE TITLE
Date patch is affecting lograge timestamp gem

### ISSUE THREAD

**Issue by andywenk** [langalex/couch_potato#105]
Hi Alex,

I am aware, that you patch Date. Now I have the issue that this patch is breaking the timestamp format in https://github.com/roidrage/lograge, more exactly in logstash-event (https://github.com/elasticsearch/logstash/blob/v1.1.5/lib/logstash/event.rb). Basically I think patching this so globally (https://github.com/langalex/couch_potato/blob/master/lib/core_ext/date.rb) is problematic as we can see here https://github.com/roidrage/lograge/issues/95

Is there a simple way to circumvent this? If not, wouldn't it be a better idea to namespace the patch like following the ideas of Justin (http://www.justinweiss.com/blog/2015/01/20/3-ways-to-monkey-patch-without-making-a-mess/).

I really love couch_potato and I love helping to fix this.

Thanks and Cheers

Andy

**Comment by langalex** [comment]
full ack. ideally the patches would be removed completely but there has to be a way for old projects to still load them manually. not sure if this could actually be a use case for ruby refinements.

**Comment by andywenk** [comment]
I try (time wise) to work on this. Do you have a preference how to include it manually? E.g. a switch in configuration settings? We could decide to use refinements depending on which Ruby version is used. refinements are available since Ruby 2.0 so this would be an indicator to use them (if it fits). When < 2.0 the patch could be included but this would mean, that it still breaks e.g. lograge.

**Comment by langalex** [comment]
I'd be happy to drop pre Ruby 2.0 support if needed. I'd say let people require the patch files manually instead of a config switch.

**Comment by andywenk** [comment]
there are many specs failing. Is this known? Or do they run for you?

**Comment by langalex** [comment]
on travis they pass. my guess is your couch doesn't have the erlang view server enabled. add this to couchdb.ini or local.ini:

    [native_query_servers]
    erlang = {couch_native_process, start_link, []}

**Comment by andywenk** [comment]
added and now still 42 failing. I am running on ruby 2.2.0 and Erlang/OTP 17 [erts-6.3]

**Comment by langalex** [comment]
i've never tested ruby 2.2 actually...

**Comment by andywenk** [comment]
Hi Alex,

any idea how to proceed here ?

Thanks and Cheers

Andy

**Comment by andywenk** [comment]
Hi Alex,

just wanted to ask again if you see a chance to integrate the changes. We are now still using the patched version from my GH account. But we are now a bit back with commits. And furthermore, we found a bug we want to fix. Any ideas here?

Thanks a lot!

Cheers

Andy

**Comment by langalex** [comment]
I guess we could use refinements where supported and fall back to a global patch (that needs to be required manually) elsewhere?

**Comment by langalex** [comment]
fixed in 4e519fe0fefacfe5826f2f4e9cbcddbc444c4f3e

**Comment by andywenk** [comment]
thanks
