### ISSUE TITLE
CouchDB Authentication

### ISSUE THREAD

**Issue by whitehat101** [langalex/couch_potato#110]
I was wondering what methods of Authentication are available. There is an example for BasicAuth on the README, but I was not able to get that to work. I found [an example on the Wiki](https://github.com/langalex/couch_potato/wiki#how-do-i-tell-couch-potato-to-use-http-authentication) and I was able to get that example working, but it feels like a workaround.

```
#401 Unauthorized -- RestClient did not pass basic auth creds
CouchPotato::Config.database_name = "http://username:password@example.com:5984/name_of_the_db"
```

If BasicAuth isn't fully supported, I'm curious what is the preferred method of Auth? Should the example above (README, not from the Wiki) be working?

**Comment by langalex** [comment]
couch potato uses [CouchRest](http://github.com/couchrest/couchrest) to talk to CouchDB, so you might want to take a look there.

**Comment by pboling** [comment]
The authentication example above *does* work in the current release.

Example here:
https://github.com/omniauth/omniauth-identity/blob/9f77c90ca78f0ccc7c760712591ace9c7ff36ace/spec_orms/couch_potato_spec.rb#L7-L9
