### ISSUE TITLE
CouchRest 2.0

### ISSUE THREAD

**Issue by samlown** [langalex/couch_potato#111]
Not strictly an issue, but I wanted to let you know that there is a release candidate for the new CouchRest gem. It has support for persistent connections and proper streaming thanks to the HTTPClient gem. Should result in a significant performance increase, but it may require a few small API changes to work with Couch Potato.

Comments and suggestions welcome: https://github.com/couchrest/couchrest & PR: https://github.com/couchrest/couchrest/pull/110

**Comment by langalex** [comment]
Thanks for letting me know. I'm pretty busy at the moment, but at the very latest, as soon as I migrate one of my own apps to 2.0, Couch Potato will be updated as well.

**Comment by langalex** [comment]
we're referencing rc3 now.

**Comment by langalex** [comment]
done
