### ISSUE TITLE
require 'couch_potato/rspec' => "cannot load such file -- rspec/matchers"

### ISSUE THREAD

**Issue by awendt** [langalex/couch_potato#69]
require 'couch_potato/rspec'

raises

    /Users/andrewen/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/couch_potato-0.7.0.pre.1/lib/couch_potato/rspec/matchers.rb:22:in `<module:RSpec>': cannot load such file -- rspec/matchers (LoadError)
	from /Users/andrewen/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/couch_potato-0.7.0.pre.1/lib/couch_potato/rspec/matchers.rb:21:in `<top (required)>'

The output of `bundle show` is:

  * activemodel (3.2.3)
  * activesupport (3.2.3)
  * addressable (2.2.7)
  * builder (3.0.0)
  * bundler (1.1.4)
  * capybara (1.1.2)
  * childprocess (0.3.2)
  * couch_potato (0.6.0)
  * couchrest (1.0.1)
  * cucumber (1.1.9)
  * daemons (1.1.8)
  * diff-lcs (1.1.3)
  * eventmachine (0.12.10)
  * fakeweb (1.3.0)
  * ffi (1.0.11)
  * gherkin (2.9.3)
  * i18n (0.6.0)
  * json (1.6.6)
  * launchy (2.1.0)
  * libwebsocket (0.1.3)
  * mime-types (1.18)
  * multi_json (1.3.2)
  * nokogiri (1.5.2)
  * oauth (0.4.6)
  * rack (1.4.1)
  * rack-protection (1.2.0)
  * rack-test (0.6.1)
  * rake (0.9.2.2)
  * rest-client (1.6.7)
  * rspec (2.9.0)
  * rspec-core (2.9.0)
  * rspec-expectations (2.9.1)
  * rspec-mocks (2.9.0)
  * rubyzip (0.9.7)
  * selenium-webdriver (2.21.2)
  * sinatra (1.3.2)
  * term-ansicolor (1.0.7)
  * thin (1.3.1)
  * tilt (1.3.3)
  * timecop (0.3.5)
  * twitter_oauth (0.4.3)
  * validatable (1.6.7)
  * xpath (0.1.4)

I haven't tried with HEAD though. If you need anything else to reproduce this, let me know.

**Comment by langalex** [comment]
fixed some time ago
